# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d223a62f4abd7948c7afc72ca7c4ac3efaf798684ebfc775a9837f068fe4bc70a832ec2a0bb09ad0b5a62e9a29a3e9ba69013ae1b6ed7b978823ed25f78e09f2

test:
  secret_key_base: eb8d937d560f08e241433541b88437a7e569afb79c081e2f74dd1bb31590c9a53ec3ff60dd765f2aa9fe2429c420f1f9076ffb6b2bfe35475765ed9d97225adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
